### ISSUE TITLE
Can't explicitly set `false` values in yml config

### ISSUE THREAD

**Issue by scottwb** [taskrabbit/waistband#15]
In configuration.rb, the `method_missing` routine will call `super` if the requested method is not found in the `@yml_config`...but it will also call `super` if the requested method _does_ exist in the `@yml_config` but returns `false`:

```ruby
    def method_missing(method_name, *args, &block)
      return @yml_config[method_name] if @yml_config[method_name]
      super
    end
```

This causes problems, for example, if I want to set in my YML file:

```
production:
  reload_on_failure: false
```

(or even omit `reload_on_failure` for that matter). The first line of `method_missing` does not return, and instead calls `super`, which raises a method not found exception.

Suggested fix: Change the `if` clause in `method_missing` to `@yml_config.has_key?(method_name)`

/cc @jgroh9

**Comment by davidjairala** [comment]
Thanks for the report and suggested fix.  Will patch tonight and update.

**Comment by davidjairala** [comment]
Had some free time at work today:
https://github.com/taskrabbit/waistband/commit/28f714f73d02c27bdabc034493d6d5bf8829577b

Let me know if that fully addresses this.

**Comment by scottwb** [comment]
Nice! I reviewed the commit and your core change to `configuration.rb` looks identical to what I did with my monkey patch:

```ruby
module Waistband
  class Configuration
    def method_missing(method_name, *args, &block)
      return @yml_config[method_name] if @yml_config.has_key?(method_name)
      super
    end
  end
end
```

That monkey patch has just been proven in production to fix my problem, so I would be 99.9% confident your patch would as well...

When do you plan to push a new version of the gem? (In the meantime, I will try sourcing the gem directly from this commit in GitHub...)

**Comment by scottwb** [comment]
Hah! I spoke too soon. I see you _did_ already release a new gem to rubygems. Grabbing it now...

**Comment by davidjairala** [comment]
Awesome.  Closing this.  Let me know if you find any other issues.  Cheers!

**Comment by scottwb** [comment]
Excellent. Thanks for the quick turnaround! I have confirmed that the new gem (0.16.2) fixes this problem in production for me.
